### ISSUE TITLE
リファクタリング後、DHTに保存されたスレッドを取得できない

### ISSUE THREAD

**Issue by Hiroyuki-Nagata** [Hiroyuki-Nagata/p2p2ch#6]
```
[info] application - building thread: aaa
[debug] application - 
--- Thread building information ---
Title: aaa
Epoch: 1434644874
Digest(SHA-1): YWFhPD4xNDM0NjQ0ODc0PD5hYWE8PmFhYTw+YWFh
Name: aaa
Mail: aaa

[debug] application - registering thread data into Chord DHT...
[debug] application - registered into Chord DHT.
[debug] application - registering thread data into local database...
[debug] application - thread information has registered successfully.
[debug] application - generating subject.txt...
[debug] application - Thread addresses in DB: 1
[debug] application - subject.txt has been generated.(1)
```

- スレを立てる
- subject.txt内にはテキストがない

@windymelt

**Comment by windymelt** [comment]
Cloneしてみてみます

**Comment by Hiroyuki-Nagata** [comment]
頼むー

**Comment by windymelt** [comment]
masterをcloneしてみましたがそのままでは動かないようです?
p2pscalaprotoに含まれるscalazのバージョンとかでしょうか？

@Hiroyuki-Nagata お手許ではどのようにして動かしていますか？

```
[error] application - 

! Internal server error, for (GET) [/bbs/subject.txt] ->

java.lang.IncompatibleClassChangeError: Found class scalaz.syntax.std.ListOps, but interface was expected
	at momijikawa.p2pscalaproto.NodeList$.apply(NodeList.scala:114) ~[p2pscalaproto_2.10-0.2.16.jar:0.2.16]
	at momijikawa.p2pscalaproto.Chord.<init>(Chord.scala:24) ~[p2pscalaproto_2.10-0.2.16.jar:0.2.16]
	at controllers.Chord2ch.<init>(Chord2ch.scala:5) ~[na:na]
	at controllers.Application$.<init>(Application.scala:26) ~[na:na]
	at controllers.Application$.<clinit>(Application.scala) ~[na:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$3$$anonfun$apply$3.apply(routes_routing.scala:121) ~[na:na]
[error] application - Error while rendering default error page
scala.MatchError: java.lang.IncompatibleClassChangeError: Found class scalaz.syntax.std.ListOps, but interface was expected (of class java.lang.IncompatibleClassChangeError)
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:131) ~[play_2.10-2.2.1.jar:2.2.1]
	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:189) [play_2.10-2.2.1.jar:2.2.1]
	at play.core.server.Server$class.logExceptionAndGetResult$1(Server.scala:73) [play_2.10-2.2.1.jar:2.2.1]
	at play.core.server.Server$$anonfun$getHandlerFor$4.apply(Server.scala:83) [play_2.10-2.2.1.jar:2.2.1]
	at play.core.server.Server$$anonfun$getHandlerFor$4.apply(Server.scala:81) [play_2.10-2.2.1.jar:2.2.1]
	at scala.util.Either$RightProjection.flatMap(Either.scala:523) [scala-library.jar:na]
```

**Comment by Hiroyuki-Nagata** [comment]
@windymelt Scalaのプロジェクトを`dependsOn`で設定すると、`~/.sbt/0.13/staging`以下にキャッシュが出来ます。それを消してからもう一度ビルドしてみて下さい。

**Comment by windymelt** [comment]
`controller.threadbuilding.ThreadBuilder`クラスでは`chord2ch`を呼んでいますが本当は`DHT.default`を呼ぶべきです。DHTに関する処理はDHT.defaultを経由して行うように抽象化しているためです。

Overlay-Weaverは使わない方針になったので`overlay-weaver`ブランチはp2pscalaprotoを使うように改正しているところです。p2pscalaproto固有の機能が抽象化で使えなくなるおそれがありますが、ひとまず使えるようにアクセス経路を用意しておきます。`windymelt/P2P2ch/master`にそちらの変更をできるだけ取り込んでmergeしてみます。そしてこちらのrepositoryをもういちど使ってみてください。

こちらのp2p2chではp2pscalaprotoは動作しています。

**Comment by windymelt** [comment]
`p2p2ch/overlay-weaver`に@Hiroyuki-Nagata さんのコミットを取り込んでみましたので確認いただけると幸いです

**Comment by Hiroyuki-Nagata** [comment]
@windymelt 
とりあえずそちらの`p2p2ch/overlay-weaver`ブランチでうまく動くことを確認しました。
お疲れ様です。たぶんISSUEが開いていると気になると思うので閉じときます。
続きは`p2p2ch/overlay-weaver`からforkしてコーディング開始かなあ。

### ご参考：こっちのmasterとの比較
https://github.com/Hiroyuki-Nagata/p2p2ch/compare/master...windymelt:overlay-weaver
全体的に`DHT.default`を使用するようにしないといけなかったようですね。
